### ISSUE TITLE
blockly-tests

### ISSUE THREAD

**Issue by mrizkii7** [gaufqwi/blockly-tests#1]
![a](https://cloud.githubusercontent.com/assets/15489405/14060911/c6a96b0e-f3a4-11e5-9085-ae6ac18cb847.JPG)
Hi, I'm Rizki.
I am interested in your blockly-tests. I have downloaded your blockly-tests. But, after I try it offline, I do not see content that I see on your web pages. I tried stored in local storage and local server. have a solution? I would like to make a maze as you make.
Sorry for bad english ehehe
Thanks

**Comment by gaufqwi** [comment]
It has been a while since I tinkered with these. You will need to install dependencies with bower (bower.io) and then do gulp-build-gridworld.
